### PR TITLE
fix: Add ScrollView adjustment automatic

### PR DESCRIPTION
**Pull request by okwasniewski**
This PR fixes content insets in examples.

### CODE REVIEW

**Comment by okwasniewski** [comment]
cc: @dylancom

Forgot to add this, but this fixes the issue

**Comment by dylancom** [comment]
Perfect!

**Comment by dylancom** [comment]
@okwasniewski Still the scrollbar is offset approx 30px. The content isn't offset but the bar on the right for some reason.
AFAIK it should touch the top?

**Comment by okwasniewski** [comment]
@dylancom My guess is that its the issue with how Native Stack lays out screens and works with safe area if you ignore safe area insets then it goes below the top bar. Probably this needs a separate issue

**Pull request merged**
