### PR TITLE
feat: introduce expo config plugin

### PR DESCRIPTION
**Pull request by okwasniewski**
This PR should close: 

- #48 
- #40 

Api of the config plugin: 

```
"plugins": [
      "react-native-bottom-tabs"
     // or 
     ["react-native-bottom-tabs", { theme: "material2" }]
 ],
```

### CODE REVIEW

**Comment by fredrikburmester** [comment]
>  ["react-native-bottom-tabs", { theme: "material2" }]

What themes are there to pick from?

**Comment by fredrikburmester** [comment]
Ah i found this: https://okwasniewski.github.io/react-native-bottom-tabs/docs/guides/android-native-styling.html

**Comment by fredrikburmester** [comment]
Another question, this does not seem to enable the native "pill" look on android. Is that not supported currently in the expo config? Thanks.

**Comment by okwasniewski** [comment]
> Another question, this does not seem to enable the native "pill" look on android. Is that not supported currently in the expo config? Thanks.

The pill is material3 theme which is the default. Just use ["react-native-bottom-tabs"] in the app.json file

**Comment by fredrikburmester** [comment]
Screenshot 2024-11-04 at 22 07 32
I did, but i can't see the pill design.

**Comment by fredrikburmester** [comment]
https://github.com/fredrikburmester/streamyfin/blob/65a6ab99721594f0e9ec4a39070ddebd34057e19/app.json#L104

**Comment by okwasniewski** [comment]
Ah you also added edge-to-edge!

This library is missing material3 style, here is a feature request tracking it: https://github.com/zoontek/react-native-edge-to-edge/issues/38

When it lands you should be able to remove bottom tabs config plugin as only one of them is needed to set the styling

**Comment by fredrikburmester** [comment]
Oh I did not know those were related, sorry. I'm confused as to why the edge-to-edge library needs the _styles_ for the bottom-tabs to look like material3?

**Comment by okwasniewski** [comment]
> Oh I did not know those were related, sorry. I'm confused as to why the edge-to-edge library needs the _styles_ for the bottom-tabs to look like material3? 

Because edge to edge also changes the Android style in styles.xml

Now they change it to AppCompat but we need an option to change it to Material3. Android styles.xml is a bit wired but they base it on inheritance

**Comment by edmiquilena** [comment]
First of all, thanks for the lib!

I'm having the same problem with the "pill" not showing,
The style is shown as material 2
image
image
 "@bottom-tabs/react-navigation": "^0.7.1" with expo SDK 52

**Pull request merged**
